
#all: orbprelim_AM

orbprelim_AM : orbprelim_AM.x

distclean: clean

clean:
	-(rm -f gmon.out core *.pro *.clo *.fga *.rwo *.fou *.fel *.cbd \
        giffv.* *.frw *.*~ *~ *.tmp *.err *.done multprop.ctc *.mou)
