clean:
	-(rm -f *.eq1 *.mev *.sec *.pre *.pro *.dmin *.fail *~ \#*\# complete \
	*.log moid_timeder.fla VAs.output VAs.err *.mou complete \
	prop.names.fail fort.23 fort.24 weakdir gmon.out err/*.err)

