.f.o:
	$(FC) $(FFLAGS) -c $*.f -o $*.o 

include ../make.flags

all: ../lib/libgauss.a

# PUBLIC LIBRARY for Vaisala method
# (the only public routines are: vaisala, vaisub sel3g and alfdel)

# Routines written by Zoran Knezevic, Mario Carpino and Andrea Milani

TELEKDT=t_elekdt.o t_elekdt_f.o elekdt.o anecc.o hypan.o ekcc1.o ra15.o ccek1.o

t_elekdt.x: $(TELEKDT) ../lib/libsuit.a
	$(FC) $(FFLAGS) $(TELEKDT) -L../lib -lsuit -o t_elekdt.x

#sel3g.o: sel3g.f
#	$(FC) -g -C -I../include -c sel3g.f

VAIS=vaisala.o vaisub.o

LIB=iodini.o sel3g.o $(VAIS) iodet.o gaussn.o gibbs.o solv8.o gauseq.o \
    gauini.o pzeros.o ccek1.o modgeq.o anecc.o hypan.o ekcc1.o elekdt.o

../lib/libgauss.a: $(LIB)
	ar r ../lib/libgauss.a $(LIB)
	$(RANLIB) ../lib/libgauss.a

depend:
	mkdep *.f *.h ../include/*.h > make.dep

clean:
	rm -f *.x *.o lib*.a *% *~ core
	rm -f ../lib/libgauss.a

distclean: clean
	../lib/deinst_src

# Windows targets
win: ..\lib\gauss.lib

..\lib\gauss.lib: $(LIB)
	lib /out:$@ $**

winclean:
	@del *.o
	@del *.pdb
	@del ..\lib\gauss.lib

# Dependencies
include make.dep
